;; -*- coding: utf-8; mode: emacs-lisp -*-

(source gnu)
(source melpa-stable)

(depends-on "cider")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "company")
(depends-on "dockerfile-mode")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "fill-column-indicator")
(depends-on "ido-at-point" :git "git@github.com:katspaugh/ido-at-point.git")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "powerline")
(depends-on "smex")
(depends-on "terraform-mode")
(depends-on "undo-tree")
(depends-on "web-mode")
(depends-on "whitespace-cleanup-mode")
(depends-on "yaml-mode")
